name: Toegevoegde waarde per bedrijfstak
description: "Select uit 'Bbp, productie en bestedingen; productie en inkomens naar bedrijfstak'"
dimensions:
  Sector:
    name: Sector
    levels:
    - 01 Landbouw
    - 02 Bosbouw
    - 03 Visserij
    - 10-12 Voedings-  genotmiddelenindustrie
    - 13-15 Textiel-  kleding-  lederindustrie
    - 16 Houtindustrie
    - 17 Papierindustrie
    - 18 Grafische industrie
    - 19 Aardolie-industrie
    - 20 Chemische industrie
    - 21 Farmaceutische industrie
    - 22 Rubber- en kunststofproductindustrie
    - 23 Bouwmaterialenindustrie
    - 24 Basismetaalindustrie
    - 25 Metaalproductenindustrie
    - 26 Elektrotechnische industrie
    - 27 Elektrische apparatenindustrie
    - 28 Machine-industrie
    - 29 Auto- en aanhangwagenindustrie
    - 30 Overige transportmiddelenindustrie
    - 31-32 Meubel- en overige industrie
    - 33 Reparatie en installatie van machines
    - 35 Energiebedrijven
    - 36 Waterleidingbedrijven
    - 37-39 Afvalbeheer
    - 41 Algemene bouw en projectontwikkeling
    - 42 Grond-  water-  en wegenbouw
    - 43 Gespecialiseerde bouw
    - 45 Autohandel en -reparatie
    - 46 Groothandel en handelsbemiddeling
    - 47 Detailhandel (niet in auto's)
    - 49 Vervoer over land
    - 50 Vervoer over water
    - 51 Vervoer door de lucht
    - 52 Opslag  dienstverlening voor vervoer
    - 53 Post en koeriers
    - 58 Uitgeverijen
    - 59-60 Film radio en t.v.
    - 61 Telecommunicatie
    - 62-63 IT- en informatiedienstverlening
    - 64 Bankwezen
    - 65 Verzekeraars en pensioenfondsen
    - 66 Overige financiële dienstverlening
    - 68 Verhuur en handel van onroerend goed
    - 69-70 Managementadvies en holdings
    - 71 Architecten-  ingenieursbureaus e.d.
    - 72 Research
    - 73 Reclamewezen en marktonderzoek
    - 74-75 Design en veterinaire diensten
    - 77 Verhuur van roerende goederen
    - 78 Uitzendbureaus en arbeidsbemiddeling
    - 79 Reisbureaus  reisorganisatie en -info
    - 80-82 Beveiliging en ov. zakelijke diens
    - 84 Openbaar bestuur en overheidsdiensten
    - 85 Onderwijs
    - 86 Gezondheidszorg
    - 87-88 Verzorging en welzijn
    - 90-92 Kunst  cultuur en loterij
    - 93 Sport en recreatie
    - 94 Ideële  belangen-  hobbyverenigingen
    - 95 Reparatie van consumentenartikelen
    - 96 Overige persoonlijke dienstverlening
    - 97 Huishoudens met personeel
    - 99 Extraterritoriale organisaties
    - A-U Alle economische activiteiten
    - B Delfstoffenwinning
    - Goederen en diensten n.e.g.
    - I Horeca
    - Totaal activiteiten en overige posten
    - Verschil toegerekende en afgedragen BTW
    aggregate: A-U Alle economische activiteiten
    default: A-U Alle economische activiteiten
    type: categorical
  Jaar:
    name: Jaar
    levels:
    - 1988
    - 1989
    - 1990
    - 1991
    - 1992
    - 1993
    - 1994
    - 1995
    - 1996
    - 1997
    - 1998
    - 1999
    - 2000
    - 2001
    - 2002
    - 2003
    - 2004
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
    - 2010
    - 2011
    aggregate: 2011
    default: 2011
    type: categorical
variables:
  BrutoToegevoegdeWaardeBasisprijzen:
    name: Bruto toegevoegde waarde basisprijzen (2005)
    type: numeric
    unit: 
    population: Bedrijven
  BrutoToegevoegdeWaardeBasisprijzenIndex:
    name: Bruto toegevoegde waarde basisprijzen (index)
    type: numeric
    unit: 
    population: Bedrijven
populations:
  Bedrijven: No population description available

