name: "participation"
longname: "Labor force participation rate"
description: "Labor force participation rate"
url: ""

variables:
  gender:
    name: gender
    type: factor
    description:
    categories: [male, female]
  generation:
    name: generation
    type: factor
    description:
    categories: ["1906-1910", "1911-1915", "1916-1920", "1921-1925", "1926-1930", "1931-1935", "1936-1940",
        "1941-1945", "1946-1950", "1951-1955", "1956-1960", "1961-1965", "1966-1970", "1971-1975",
        "1976-1980", "1981-1985", "1986-1990"]
  age:
    name: age
    type: integer

slices: [gender, generation, age, variable, value]