JSHEAD <- "//
// Autogenerated javascript functions that call R functions.
// Communication is in JSON
var R = window.R = {
"
JSEND <- "};\n"


#' automatically generates an ajax handler for a list of R functions
ajaxify <- function(list=NULL){
  
  # TODO 
  # Source all files in a certain  directory  
  
  jsf <- character()
  for (n in list) {
    fn <- eval(as.symbol(n))
    if (is.function(fn)){
      jsf <- c(jsf, wrapJS(fn, name=n))
    }
  }

  js <- paste(JSHEAD, paste(jsf, collapse=",\n"), JSEND)
  
  cat("Generating './www/js/R.js...\n'")
  
  writeLines(js, "./www/js/R.js")
  #' dispatches the url to the correct function
  dispatch <- function(env){
    
    req <- Rook::Request$new(env)
    f <- gsub("^.+/R/", "", req$path())
    params <- get_params(req)
    
    res <- Rook::Response$new()
    res$header("Content-Type", "application/json")  
  
    tryCatch({
          params <- lapply(params, fromJSON)
          print(str(params))
          result <- do.call(f, params)
          # TODO write nested data frames the correct way
          if (is.data.frame(result)){
            json <- df_to_json(result)
          } else {
            json <- toJSON(result)
          }
          res$write(json)
        }
        , error=function(e){ res$write(toJSON(list(fail=TRUE, message=as.character(e))))}
        )
    res$finish()
  }
  
  dispatch
}
  
wrapJS <- function(f, name=deparse(substitute(f))){
  arg <- names(formals(f))
  
  obj <- paste0("\t\tif (",arg," !== undefined) $data['",arg,"'] = JSON.stringify(",arg,");\n", collapse="")
  
  arg <- paste(arg, collapse=", ")
  url <- paste0("./R/", name)
  paste0("\t",name,": function(", arg, "){\n"
        , "\t\tvar $data = {};\n"
        , obj
        , "\t\treturn $.ajax({\n"
        , "\t\t\turl: '", url, "',\n"
        ,  "\t\t\tdataType:'json',\n"
        ,  "\t\t\ttype:'POST',\n"
        ,  "\t\t\tdata: $data});\n"
        , "\t\t}"
        )
}

#ajaxify("list_tables") -> l